package com.github.thi747.tespat.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class FornecedorAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFornecedorAllPropertiesEquals(Fornecedor expected, Fornecedor actual) {
        assertFornecedorAutoGeneratedPropertiesEquals(expected, actual);
        assertFornecedorAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFornecedorAllUpdatablePropertiesEquals(Fornecedor expected, Fornecedor actual) {
        assertFornecedorUpdatableFieldsEquals(expected, actual);
        assertFornecedorUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFornecedorAutoGeneratedPropertiesEquals(Fornecedor expected, Fornecedor actual) {}

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFornecedorUpdatableFieldsEquals(Fornecedor expected, Fornecedor actual) {
        assertThat(expected)
            .as("Verify Fornecedor relevant properties")
            .satisfies(e -> assertThat(e.getNome()).as("check nome").isEqualTo(actual.getNome()))
            .satisfies(e -> assertThat(e.getDescricao()).as("check descricao").isEqualTo(actual.getDescricao()))
            .satisfies(e -> assertThat(e.getCpfOuCnpj()).as("check cpfOuCnpj").isEqualTo(actual.getCpfOuCnpj()))
            .satisfies(e -> assertThat(e.getEmail()).as("check email").isEqualTo(actual.getEmail()))
            .satisfies(e -> assertThat(e.getTelefone()).as("check telefone").isEqualTo(actual.getTelefone()))
            .satisfies(e -> assertThat(e.getEndereco()).as("check endereco").isEqualTo(actual.getEndereco()))
            .satisfies(e -> assertThat(e.getCidade()).as("check cidade").isEqualTo(actual.getCidade()))
            .satisfies(e -> assertThat(e.getEstado()).as("check estado").isEqualTo(actual.getEstado()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFornecedorUpdatableRelationshipsEquals(Fornecedor expected, Fornecedor actual) {}
}
