package com.github.thi747.tespat.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class LocalAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertLocalAllPropertiesEquals(Local expected, Local actual) {
        assertLocalAutoGeneratedPropertiesEquals(expected, actual);
        assertLocalAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertLocalAllUpdatablePropertiesEquals(Local expected, Local actual) {
        assertLocalUpdatableFieldsEquals(expected, actual);
        assertLocalUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertLocalAutoGeneratedPropertiesEquals(Local expected, Local actual) {}

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertLocalUpdatableFieldsEquals(Local expected, Local actual) {
        assertThat(expected)
            .as("Verify Local relevant properties")
            .satisfies(e -> assertThat(e.getNome()).as("check nome").isEqualTo(actual.getNome()))
            .satisfies(e -> assertThat(e.getDescricao()).as("check descricao").isEqualTo(actual.getDescricao()))
            .satisfies(e -> assertThat(e.getSala()).as("check sala").isEqualTo(actual.getSala()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertLocalUpdatableRelationshipsEquals(Local expected, Local actual) {}
}
